### ISSUE TITLE
field for price

### ISSUE THREAD

**Issue by cdofitas** [mjsolidarios/bee-delivery-public#2]
field price in order are not yet added

this is to compute the base price of the product then compute to the price percentage of bee pricing

base price *20%(depending  their set percentage)

![Capture](https://user-images.githubusercontent.com/71762751/105042212-ef3cbd80-5a9e-11eb-8235-243b0a412f0b.PNG)

ano siya mark?

**Comment by mjsolidarios** [comment]
Already implemented
